### ISSUE TITLE
expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by umairjavaid** [clovaai/wsolevaluation#23] opened 2020-06-19 22:24 UTC
Getting the above issue after running the following commands

!git clone https://github.com/clovaai/wsolevaluation.git
os.chdir("wsolevaluation")
!bash dataset/prepare_cub.sh

!python main.py --dataset_name CUB \
               --architecture vgg16 \
               --wsol_method cam \
               --experiment_name cub_vgg16 \
               --pretrained TRUE \
               --num_val_sample_per_class 0 \
               --large_feature_map TRUE \
               --batch_size 32 \
               --epochs 50 \
               --lr 0.000227913316 \
               --lr_decay_frequency 15 \
               --weight_decay 1.00E-04 \
               --override_cache FALSE \
               --workers 4 \
               --box_v2_metric True \
               --iou_threshold_list 30 50 70 \
               --eval_checkpoint_type last

**Comment by umairjavaid** [comment] 2020-06-19 22:24
Start epoch 0 ...
Evaluate epoch 0, split val
Computing and evaluating cams.
Traceback (most recent call last):
  File "main.py", line 416, in <module>
    main()
  File "main.py", line 387, in main
    trainer.evaluate(epoch=0, split='val')
  File "main.py", line 309, in evaluate
    cam_performance = cam_computer.compute_and_evaluate_cams()
  File "/content/wsolevaluation/inference.py", line 90, in compute_and_evaluate_cams
    cam_path = ospj(self.log_folder, 'scoremaps', image_id)
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by junsukchoe** [comment] 2020-06-20 04:27
I followed your instruction, but unfortunately I could not reproduce your error.
Could you let me know which of the two variables (`self.log_folder` and `image_id`) is `NoneType`?

**Comment by coallaoh** [comment] 2020-07-06 22:52
Closing the issue, assuming the question was answered :)
Please re-open the issue as necessary.

**Closed by coallaoh** 2020-07-06 22:52 UTC
